### ISSUE TITLE
Fails on next 12.1.6

### ISSUE THREAD

**Issue by karl-run** [scottrippey/next-router-mock#51]
I'm upgrading my app from 12.1.2 to 12.1.6 and it seems some internal next paths have changed, causing the patching to fail.

When I run my tests:

```bash
    Cannot find module 'next/dist/server/normalize-page-path' from 'node_modules/next-router-mock/dist/dynamic-routes/extensions-11.1.js'

    Require stack:
      node_modules/next-router-mock/dist/dynamic-routes/extensions-11.1.js
      jest.setup.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (node_modules/next-router-mock/src/dynamic-routes/extensions-11.1.ts:9:1)
```

**Comment by karl-run** [comment]
After comparing the [changes between 12.1.5 and 12.1.6](https://github.com/vercel/next.js/compare/38d17bca0c34ebcc3055dbdfc42bfff26f88f62e...b188fab3360855c28fd9407bd07c4ee9f5de16a6#diff-9c1a3867443c54525b4f24ef171f231a6e8bb065ffc8b7b62c4843d5ff62dd42) I can see that the file in question has been moved.

From:
`packages/next/server/denormalize-page-path.ts`
To:
`packages/next/shared/lib/page-path/denormalize-page-path.ts`

**Comment by scottrippey** [comment]
FWIW, with the latest publish `0.7.0`, you don't need the `/next-12` path.  You can import like:
```
import { createDynamicRouteParser } from "next-router-mock/dynamic-routes";
```
See the newly updated docs, to see how to upgrade.
